<!-- Start of footer -->
	<TR>
		<TD align=center bgColor=#ddddff class="solidBorder">
			<TABLE width="90%"><TR>

	<TD align="left">

		<A HREF="http://citg.uthsc.edu/" target="_blank">

		<IMG SRC="/images/upload/CITGLogo.png" alt="CITG" border="0"></A>

	</TD>

	<TD align="left" id="smallsize" style="font-size:11px;font-family:verdana;color:black">

WWW service initiated January, 1994 as <A HREF="http://www.ncbi.nlm.nih.gov/pubmed?term=8043953">The Portable Dictionary of the Mouse Genome</A> and June 15, 2001 as WebQTL. 



This site is currently operated by

		<A class="smallsize" HREF="mailto:rwilliams@uthsc.edu">Rob Williams</A>,

		<A class="smallsize" HREF="mailto:lyan6@uthsc.edu">Lei Yan</A>,

		<A class="smallsize" HREF="mailto:zachary.a.sloan@gmail.com">Zachary Sloan</A>,

		<A class="smallsize" HREF="mailto:acenteno@uthsc.edu" target="_blank">Arthur Centeno</A>. Design and code by Sam Ockman, Xiaodong Zhou, Christian Fernandez, Ning Liu, Rudi Alberts, Elissa Chesler, Jintao Wang, Kenneth Manly, Robert W. Williams, and <A class="smallsize" HREF="/credit.html">colleagues</A>.





	</TD>

	<TD align="right">

		<A HREF="http://www.python.org/" target="_blank">

		<IMG src="/images/upload/PythonLogo.png" alt="Python Powered" border="0"></A>

	</TD>

	<TD align="right">

		<A HREF="http://www.neuinfo.org"  target="_blank">

		<img src="/images/upload/Nif.png" alt="Registered with Nif" border="0"></A>

	</TD>

</TR>

<TR>



<!--  GENENETWORK SUPPORTED BY  -->



	<TD colspan=4  style="font-size:12px;font-family:verdana;color:black">

		GeneNetwork support from:

		<UL>

		<LI><a class="smallsize" target="_blank" href="http://citg.uthsc.edu">The UT Center for Integrative and Translational Genomics</A>

		<LI><a class="smallsize" target="_blank" href="http://www.iniastress.org">NIAAA</A> Integrative Neuroscience Initiative on Alcoholism (U01 AA016662, U01 AA013499, U24 AA013513, U01 AA014425)

		<LI><a class="smallsize" target="_blank" href="http://www.drugabuse.gov/about/organization/Genetics/geneexpression/index.html">NIDA</A>, <a class="smallsize" target="_blank" href="http://www.nimh.nih.gov/">NIMH</A>, and <a class="smallsize" target="_blank" href="http://www.niaaa.nih.gov/">NIAAA</A> (P20-DA 21131)

		<LI>NCI <a class="smallsize" target="_blank" href="http://emice.nci.nih.gov/">MMHCC</A> (U01CA105417), <a class="smallsize" target="_blank" href="http://www.ncrr.nih.gov/">NCRR</A> <a class="smallsize" target="_blank" href="http://www.nbirn.net/TestBeds/Mouse/index.htm">BIRN</A>,  (U24 RR021760)

		</UL>

	</TD>

</TR>

<TR>

	<TD colspan=4 id="smallsize" align="left">

		&nbsp;&nbsp;&nbsp;&nbsp;<a target="_blank" href="http://atlas.uthsc.edu/mailman/listinfo/genenetwork">Join GeneNetwork Mailing List</a>

	</TD>

</TR>

<TR>

	<TD colspan=4 id="smallsize" align="left">

		&nbsp;&nbsp;&nbsp;&nbsp;

	</TD>

</TR>

</table>
		</td>
	</TR>
	<!-- End of footer -->
</TABLE>

<!-- menu script itself. you should not modify this file -->
<script language="JavaScript" src="/javascript/menu_new.js"></script>
<!-- items structure. menu hierarchy and links are stored there -->
<script language="JavaScript" src="/javascript/menu_items.js"></script>
<!-- files with geometry and styles structures -->
<script language="JavaScript" src="/javascript/menu_tpl.js"></script>
<script language="JavaScript">
	<!--//
	// Note where menu initialization block is located in HTML document.
	// Don't try to position menu locating menu initialization block in
	// some table cell or other HTML element. Always put it before </body>
	// each menu gets two parameters (see demo files)
	// 1. items structure
	// 2. geometry structure
	new menu (MENU_ITEMS, MENU_POS);
	// make sure files containing definitions for these variables are linked to the document
	// if you got some javascript error like "MENU_POS is not defined", then you've made syntax
	// error in menu_tpl.js file or that file isn't linked properly.
	
	// also take a look at stylesheets loaded in header in order to set styles
	//-->
</script>
</BODY>
</HTML>
