ctext = ''
ctext += '<TR>'
ctext += '	<TD align="left">'
ctext += '		<A HREF="http://citg.uthsc.edu/" target="_blank">'
ctext += '		<IMG SRC="/images/upload/CITGLogo.png" alt="CITG" border="0"></A>'
ctext += '	</TD>'
ctext += '	<TD align="left" id="smallsize" style="font-size:11px;font-family:verdana;color:black">'
ctext += 'WWW service initiated January, 1994 as <A HREF="http://www.ncbi.nlm.nih.gov/pubmed?term=8043953">The Portable Dictionary of the Mouse Genome</A> and June 15, 2001 as WebQTL.'
ctext += ''
ctext += 'This site is currently operated by'
ctext += '		<A class="smallsize" HREF="mailto:rwilliams@uthsc.edu">Rob Williams</A>,'
ctext += '		<A class="smallsize" HREF="mailto:lyan6@uthsc.edu">Lei Yan</A>,'
ctext += '		<A class="smallsize" HREF="mailto:pjotr.public32@thebird.nl">Pjotr Prins</A>,'
ctext += '		<A class="smallsize" HREF="mailto:zachary.a.sloan@gmail.com">Zachary Sloan</A>,'
ctext += '		<A class="smallsize" HREF="mailto:acenteno@uthsc.edu" target="_blank">Arthur Centeno</A>. Design and code by Pjotr Prins, Lei Yan, Zach Sloan, Arthur Centeno, Kenneth Manly, Jintao Wang, Danny Arends, Christian Fischer, Sam Ockman, Xiaodong Zhou, Christian Fernandez, Ning Liu, Rudi Alberts, Elissa Chesler, Evan G. Williams, Alexander G. Williams, and Robert W. Williams, and <A class="smallsize" HREF="/credit.html">colleagues</A>.'
ctext += ''
ctext += ''
ctext += '	</TD>'
ctext += '	<TD align="right">'
ctext += '		<A HREF="http://www.python.org/" target="_blank">'
ctext += '		<IMG src="/images/upload/PythonLogo.png" alt="Python Powered" border="0"></A>'
ctext += '	</TD>'
ctext += '	<TD align="right">'
ctext += '		<A HREF="http://www.neuinfo.org"  target="_blank">'
ctext += '		<img src="/images/upload/Nif.png" alt="Registered with Nif" border="0"></A>'
ctext += '	</TD>'
ctext += '</TR>'
ctext += '<TR>'
ctext += ''
ctext += '<!--  GENENETWORK SUPPORTED BY  -->'
ctext += ''
ctext += '	<TD colspan=4  style="font-size:12px;font-family:verdana;color:black">'
ctext += '		GeneNetwork support from:'
ctext += '		<UL>'
ctext += ''
ctext += '<LI><a class="smallsize" target="_blank" href="http://citg.uthsc.edu">The UT Center for Integrative and Translational Genomics</A>'
ctext += ''
ctext += '<LI><a class="smallsize" target="_blank" href="https://www.nigms.nih.gov">NIGMS</A> Systems Genetics and Precision Medicine project (R01 GM123489, 2017-2021)'
ctext += ''
ctext += '<LI><a class="smallsize" target="_blank" href="https://www.drugabuse.gov">NIDA</A> NIDA Core Center of Excellence in Transcriptomics, Systems Genetics,'
ctext += 'and the Addictome (P30 DA044223, 2017-2022)'
ctext += ''
ctext += '<LI><a class="smallsize" target="_blank" href="http://www.nia.nih.gov">NIA</A> Translational Systems Genetics of Mitochondria, Metabolism, and Aging (R01AG043930, 2013-2018)'
ctext += ''
ctext += '<LI><a class="smallsize" target="_blank" href="http://www.iniastress.org">NIAAA</A> Integrative Neuroscience Initiative on Alcoholism (U01 AA016662, U01 AA013499, U24 AA013513, U01 AA014425, 2006-2017)'
ctext += ''
ctext += '<LI><a class="smallsize" target="_blank" href="http://www.drugabuse.gov">NIDA</A>, <a class="smallsize" target="_blank" href="http://www.nimh.nih.gov/">NIMH</A>, and <a class="smallsize" target="_blank" href="http://www.niaaa.nih.gov/">NIAAA</A> (P20-DA 21131, 2001-2012)'
ctext += ''
ctext += '<LI>NCI <a class="smallsize" target="_blank" href="http://emice.nci.nih.gov/">MMHCC</A> (U01CA105417), NCRR, <a class="smallsize" target="_blank" href="http://www.birncommunity.org">BIRN</A>, (U24 RR021760)'
ctext += '		</UL>'
ctext += '	</TD>'
ctext += '</TR>'
ctext += '<TR>'
ctext += '	<TD colspan=4 id="smallsize" align="left">'
ctext += '		&nbsp;&nbsp;&nbsp;&nbsp;<a target="_blank" href="http://atlas.uthsc.edu/mailman/listinfo/genenetwork">Join GeneNetwork Mailing List</a>'
ctext += '	</TD>'
ctext += '</TR>'
ctext += '<TR>'
ctext += '	<TD colspan=4 id="smallsize" align="left">'
ctext += '		&nbsp;&nbsp;&nbsp;&nbsp;<!-- %s -->'
ctext += '	</TD>'
ctext += '</TR>'
document.write(ctext)